### ISSUE TITLE
Strumieniowanie baz danych z plikami VCF, GFF i BED

### ISSUE THREAD

**Issue by ejdzi** [hansiu/bio-VCF#13]
Dodanie do fetchy możliwości pobrania danych bezpośrednio z baz danych

**Comment by ejdzi** [comment]
Fetch na strumieniu pliku GFF działający na wersjach pythona 2.7 i 3.4 --> zrobione

**Comment by ejdzi** [comment]
Fetch na strumieniu pliku BED działający na wersjach pythona 2.7 i 3.4 --> zrobione

**Comment by hansiu** [comment]
eee yy tak, to jest skończone :d
