### ISSUE TITLE
Testy biopythonowe

### ISSUE THREAD

**Issue by hansiu** [hansiu/bio-VCF#3]
Przeniesienie plików z danymi do testów do bio-VCF/Tests/VCF.
Dodanie innych znalezionych danych do tegoż folderu.
Przeniesienie i poprawienie skryptów testujących do bio-VCF/Tests/test_VCF.py

**Comment by hansiu** [comment]
Przeniesiono pliki z danymi z pyVCF/vcf/tests do bio-VCF/Tests/VCF i plik test_vcf.py zmieniono na test_VCF.py oraz dodano do bio-VCF/Tests.

Brakuje:

- dodania danych naszych

- pliku prof.py z pyVCF/vcf/tests (zastanowić się co z nim)

Poprawienie skryptów testujących to sprawa na osobne issue.

**Comment by Zincc** [comment]
ZROBIWSZY!1111 oneoneone
