### ISSUE TITLE
hap

### ISSUE THREAD

**Issue by ejdzi** [hansiu/bio-VCF#4]
ftp://ftp.hapmap.org/hapmap/phasing/2009-02_phaseIII/HapMap3_r2/

stąd

**Comment by ejdzi** [comment]
Mamy dane z phasing i mamy dane np. z pliku VCF. Chcemy mieć te haplotypy, których SNP są w tym pliku VCF. 
Przede wszystkim mamy się skupić na opracowaniu jakiegoś formatu danych dla plików z "genotype phasing", opracować jakiś rodzaj fetcha na tych danych i sposób w jaki zwracane będą haplotypy.

(Tworzenie haplotypów -->Na podstawie VCF filtrujemy wiersze, na podstawie kolumn znajdujemy bloki).

**Comment by hansiu** [comment]
zrobione, testy też.
