### ISSUE TITLE
INSTRUKCJA/DOKUMENTACJA

### ISSUE THREAD

**Issue by hansiu** [hansiu/bio-VCF#46]
trzeba opisać każdą część tak jak w biopython cookbooku

[http://biopython.org/DIST/docs/tutorial/Tutorial.html#htoc89](url)

musicie to zrobić w latex'u. Jeśli któraś jest bardzo nielatexowa, to niech chociaż tekst i przykłady z tym co powinny wypluć przygotuje.

Agnieszka już dodała swoje dwa chaptery, chociaz jeszcze ich nie przejrzałam, ale macie wstępnie za przykład:

[https://github.com/hansiu/bio-VCF/pull/43](url)

[https://github.com/hansiu/bio-VCF/pull/45](url)

**Comment by Zojka** [comment]
hmm. Page Not Found?

edit: klikanie nie działa ;)

**Comment by hansiu** [comment]
ach, pewnie przy klikaniu nie łapie że jest się zalogowanym.
tak więc, ostrzeżenie dla nastęnych zaglądających tu laski: nie klikajcie w linki tylko przekopiujcie ;)

**Comment by hansiu** [comment]
połączyłam je w jeden plik:
https://github.com/hansiu/bio-VCF/commit/cec4c20acee360b754ee106c0393537af4c51231

będzie nieco do redakcji, bo np. instrukcje jak korzystac readera są potrzebne wcześniej, ale tym się będziemy zajmować mam nadzieję @KarolinaD i @Zincc w weekend razem

**Comment by hansiu** [comment]
czesc @Zojka, @ejdzi i @hansiu gotowe, glowny trzeba jeszcze sformatowac i dodac od dziewczyn
