### ISSUE TITLE
kompatybilność python 3

### ISSUE THREAD

**Issue by hansiu** [hansiu/bio-VCF#8]
kompatybilność z pythonem 3, przede wszystkim 3.4 i 3.5
(przy importowaniu, działanie odpowiednie itp, ale na zasadach biopythonowych)

**Comment by hansiu** [comment]
#workinprogress jeśli chodzi o główne pliki. Przy from Bio import VCF działa ok (testowane na 3.5)

**Comment by hansiu** [comment]
stestowane na komendach z https://pyvcf.readthedocs.io/en/latest/
poprawione, działa.
czeka kompatybilność testów i skryptów

**Comment by ejdzi** [comment]
fetche działają z python3.4
